notifications:
  email: false

branches:
  only:
    - master

language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt build
  - grunt test
  - grunt coveralls
